### ISSUE TITLE
about method and paper

### ISSUE THREAD

**Issue by ljxalpha** [ArvinZhuang/adaptiveOLTR#1]
Would you please give me a relevant paper? 
And there is another OLTR project in your repository. Which paper is it related to?

Thank you!

**Comment by ArvinZhuang** [comment]
Hi there

Yeah, this adaptiveOLTR repo is actually my test code, the real code is in OLTR which contains two projects right now, one is published and another one is still in review. If you get interesting, the scrips (typically run_ECIR_COLTR.py) in experiments folder are for my published paper "Counterfactual Online Learning to Rank", you can find it here http://ielab.io/publications/arvin-2020-counterfactual.

**Comment by ljxalpha** [comment]
I downloaded this paper, thank you very much
